### ISSUE TITLE
shows timer on miscellania maple trees

### ISSUE THREAD

**Issue by Squimbert** [CreativeTechGuy/tree-despawn-timer#1]
the timer appears on the maple trees in miscellania which cannot be cut down, nor can you get logs from them. can you blacklist these trees?

**Comment by CreativeTechGuy** [comment]
Yup seems reasonable. Will do.

**Comment by CreativeTechGuy** [comment]
It will be out in the next release. Do note that Plugin Hub reviews have been slow lately so it may take a few weeks before you see the change in-game.
