### ISSUE TITLE
need to remove timers on farming guild plot

### ISSUE THREAD

**Issue by Squimbert** [CreativeTechGuy/tree-despawn-timer#10]
![image](https://github.com/CreativeTechGuy/tree-despawn-timer/assets/99698377/1cf4e43c-c707-4e09-8cfc-12b489b23060)

https://oldschool.runescape.wiki/w/Redwood_tree_(Farming)

according to the wiki above, redwoods grown by the player in the farming guild have a 1/11 chance per log to deplete unlike other trees. makes the timers from your plugin persist when they deplete and overlap with regular timers.

**Comment by CreativeTechGuy** [comment]
Oh that's entirely a mistake. No farming trees should be affected by this plugin. I'll fix that ASAP. Thank you for letting me know!

**Comment by CreativeTechGuy** [comment]
Weird. It looks like I tried to omit Farming Guild Redwoods before... Maybe the ids changed or maybe I got it wrong. Anyway it's being fixed now.

**Comment by CreativeTechGuy** [comment]
It has been fixed! You can track the release to RuneLite here: https://github.com/runelite/plugin-hub/pull/5802
