### ISSUE TITLE
Overlapping with Tree Count due to rendering the respective overlays at different locations on the tree

### ISSUE THREAD

**Issue by Speeddymon** [CreativeTechGuy/tree-despawn-timer#11]
Hey! I'm attaching a screenshot to demonstrate. Basically, depending on the camera angle, I end up with the timer from this plugin and the count of woodcutters on the tree from Tree Count overlapping each other. I can partially mitigate the issue by changing the colors of each plugins' respective text outputs but its still difficult to read.

![image](https://github.com/CreativeTechGuy/tree-despawn-timer/assets/1396056/183a2102-24d4-4cc9-ae95-560b6463d6b2)

You can see the green underneath the yellow here.

I was wondering if you'd be open to considering relocating the timer in this plugin to the same attachment point on the tree as the count from Tree Count?

I looked and while I'm not great with Java, I'm learning, and it looks like line 80 in `TreeDespawnTimerOverlay.java` is setting the point to the base of the tree `point` from line 43, while Tree Count attaches to the center of the tree's click box. This causes the two to overlap instead of moving together seamlessly when the camera angle changes.

Thanks in advance.

**Comment by CreativeTechGuy** [comment]
Hi. I'd like to understand the use-case of having both the Tree Count plugin and the Tree Despawn Timer plugin installed? As far as I understand, the Tree Despawn Timer plugin should address the main use cases of the Tree Count plugin (the timer changes to indicate when 10+ people are chopping a tree).

**Comment by Speeddymon** [comment]
Sure! Primarily, I use a couple of debug options in that plugin in an unconventional way. I have sight issues so I use the tree hull drawing debug option to make the click box more visible. I also use the Show Player Orientation indicator when I'm in the wild to make it easier for me to tell if someone is about to try to PK me; like let's say their direction changes from south to northeast, and I'm northeast of them at the fountain of rune, I'll see that and know to get ready for a fight.

Additionally, the exact count of choppers is helpful to visually know exactly how many people over the maximum bonus are on a tree so I can decide to hop to another tree with fewer people actively chopping (to try to maximize the bonus across an area).

Now that I'm thinking about this, I have a feature request for Tree Count I'll be submitting as well for my sight issue. It would be helpful if the tree's click box changed to a different color when there are more than 10 players.

Anyway, those are the use cases I have. It would be great if the two overlays can play better together regardless of my own personal use-cases though.

**Comment by CreativeTechGuy** [comment]
Thank you for sharing! I ask because I don't think the two plugins are ideal to be used together. They totally can be, but they are designed to be used just one or the other because they have a huge overlap of features for most people.

I don't think there's a great way to have them not overlap. I think if either plugin moved the anchor point, they'd overlap all the time since they'd always be placed on top of each other.

Technically, the only solution I can think of is if both plugins anchored to the same world space, but one of them offset the position in screen space so the text would have the same origin and rotate together, but one would be placed above the other on the screen. For that, the plugin would likely need to detect the presence of the other to know to move out of the way. But then it'd only work for that specific plugin. If any other plugin in the future added some overlay on a tree, it'd have the same issue again.

**Comment by Speeddymon** [comment]
Understood, thanks. No worries.

Since this is more for my own personal accessibility issues, I have another idea.

Would you consider accepting a PR to have your overlay display the exact count? Typically, if I see there's over 10 people chopping on one tree, but only 1 person chopping a second tree, I'll stay where I am but if there's over 10 on one and 8 or 9 on another, I'll move over to the second tree. So the exact count feature is really handy for distribution of the bonus.

I was thinking if Tree Despawn Timer would display the exact count, then I can just disable Tree Count or hot patch its primary use-case (the count overlay) to not display in my local copy while repurposing its debug features for my personal accessibility needs :)

**Comment by CreativeTechGuy** [comment]
There is a debug mode for Tree Despawn Timer which can show additional information like the number of players chopping a tree. It has slightly more information than what you want, but it's already built-in so you can easily enable it without any code changes.

In the settings set Debug Level to `Verbose` and you'll be able to see something like this:

![image](https://github.com/CreativeTechGuy/tree-despawn-timer/assets/12002072/975dc70e-6628-49e5-873d-d8962985e821)

**Comment by Speeddymon** [comment]
perfect, thanks!

**Comment by Speeddymon** [comment]
Oh, whoa, lots of chat spam with that option. Not quite as perfect. :(

**Comment by CreativeTechGuy** [comment]
The chat messages should be properly tagged as game chat so if you switch to a different chat tab then you won't see those.

But yeah there are debug messages in chat since this is a debug mode intended for developers unfortunately.
