### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Tiny-Peanuts** [CreativeTechGuy/tree-despawn-timer#2]
Could the font of the tick timer maybe have a bold option?
Seems just a little small to me while chopping redwoods on my own. Or possibly make it bigger if popular tree option is not enabled.

Thanks

**Comment by CreativeTechGuy** [comment]
What about a generic UI scale option? So you can set a multiplier so that everything is larger by a configurable percentage? Or do you think that everything is a good size except the tick timer when you are solo?
