### ISSUE TITLE
New Felling Axes not registering tree hits

### ISSUE THREAD

**Issue by Spectrahx** [CreativeTechGuy/tree-despawn-timer#3]
Hello, I realize this update just came out but didn't see it reported yet so wanted to get this info to you.

The new 2h axe (known as "Felling Axe" in game) does not engage the timer on a tree when woodcutting.

**Comment by CreativeTechGuy** [comment]
Awesome! I was waiting for this update but it's nice to know that people care enough about the plugin to come let me know. 😃 Glad you are enjoying it.

I'll get the update out ASAP, but the RuneLite plugin hub approval time can often be pretty long so it might be a bit until it's available to use in-game, sorry!

**Comment by CreativeTechGuy** [comment]
If you want to track the update being released: https://github.com/runelite/plugin-hub/pull/5114

**Comment by CreativeTechGuy** [comment]
Thank you @ArtimosPenguidor and @Skretzo for your plugins which enabled me to quickly find the new animation IDs without having all of the expensive 2H axes myself. Couldn't have done it without your work!

**Comment by ArtimosPenguidor** [comment]
Seems people get more use out of my plugin's debug features than the actual plugin! Haha. Maybe I'll pull that out into its own plugin with an actual GUI interface.

**Comment by CreativeTechGuy** [comment]
@Spectrahx well that was fast. The update is live! Restart RuneLite and it should auto-update.
