### ISSUE TITLE
Despawn pies clashing with 'woodcutting' plugin respawn timers

### ISSUE THREAD

**Issue by otygah** [CreativeTechGuy/tree-despawn-timer#6]
Not a technical issue, but being able to customize how the pies are coloured/displayed would be welcomed as in its current state it can be hard to differentiate between despawn and respawn timers on trees (especially when using popular tree indicator).

**Comment by CreativeTechGuy** [comment]
Hi! Sorry I never received a notification for this issue for some reason.

I'll look at adding more UI customization options in the next release! Thanks. 😄
