### ISSUE TITLE
Timer does not start with felling axe no logs

### ISSUE THREAD

**Issue by JakeTurnick** [CreativeTechGuy/tree-despawn-timer#7]
Felling axe provides a 20% chance to not receive a log, if this happens for your first 'cut' the timer will not start.

Trigger event is probably inventory related instead of xp related - this may also be the case for infernal axe (untested)

**Comment by CreativeTechGuy** [comment]
Good catch! Yup it's currently when you get the chat message that you received a log (same way that the RuneLite Woodcutting plugin tracks logs chopped). I'll change it to XP that seems better.

**Comment by CreativeTechGuy** [comment]
You can track the release of this fix [here](https://github.com/runelite/plugin-hub/pull/5410).

Thank you for reporting!
