### ISSUE TITLE
Incompatable with Varlamore update

### ISSUE THREAD

**Issue by Crystalius7** [CreativeTechGuy/tree-despawn-timer#8]
Runelite says the author has to update the plugin. Would be great if you could find some time.

**Comment by CreativeTechGuy** [comment]
Will do! I'm surprised the update broke it, but I guess the update also accidentally deleted some trees so who knows what weird things happen. haha

**Comment by CreativeTechGuy** [comment]
The change is waiting for RuneLite to review. You can follow the release here: https://github.com/runelite/plugin-hub/pull/5722
