### ISSUE TITLE
Yew Trees missing Timers - Shayzien

### ISSUE THREAD

**Issue by pudding437** [CreativeTechGuy/tree-despawn-timer#9]
The two trees near the Shayzien bank (1501, 3582, 0 and 1494, 3582, 0) are missing despawn timers when the are being chopped.

**Comment by pudding437** [comment]
![shayzienYews](https://github.com/CreativeTechGuy/tree-despawn-timer/assets/89750770/a892d341-64e0-40a1-818d-2792da9624bd)

**Comment by CreativeTechGuy** [comment]
Appreciate the detailed information! Will investigate today

**Comment by CreativeTechGuy** [comment]
(Also I'm jealous of your ping haha, my best case scenario is 30-50ms)

**Comment by CreativeTechGuy** [comment]
I found the issue, [apparently Shayzien has it's own special yew trees](https://oldschool.runescape.wiki/w/Yew_tree#Shayzien).

**Comment by CreativeTechGuy** [comment]
You can track the release of the new version here: https://github.com/runelite/plugin-hub/pull/5735

Thank you for reporting!

**Comment by CreativeTechGuy** [comment]
@sllnky Thank you for reporting! It's always surprising there's so many different IDs for seemingly the same looking tree.

I've fixed the issue. You can track the release here: https://github.com/runelite/plugin-hub/pull/5946

**Comment by sllnky** [comment]
@CreativeTechGuy - honestly, thank you so much. Your plugin is amazing and I really appreciate the quick resolution!

**Comment by CreativeTechGuy** [comment]
@sllnky Please don't hesitate to make a new issue if you find any other trees missing. It's really hard to check the entire game for that one random tree which is technically different but looks the same. 😛 Thanks!
